### ISSUE TITLE
Irotoridori No Sekai translation

### ISSUE THREAD

**Issue by linakima** [xmoeproject/ShinkuToolset#1]
Hi!
I would like to translate the game Irotoridori no Sekai HD (eng).
I can't get the text with FVPTextExtract, but I can disassemble it with FVPDeasm.
But I don't know how to put the translated text back into the .hcb file.
Can you help me?
[files.zip](https://github.com/xmoezzz/ShinkuToolset/files/14318387/files.zip)

**Comment by xmoezzz** [comment]
You have two options for repack:
1. Re-compile the hcb file. However, the English translation may be longer than the original Japanese text, so we'll need a complete hcb script 'assembler'. Currently, I'm working on porting the FVP engine to multiple platforms in my spare time (see this project: https://github.com/xmoezzz/rfvp), so I can't guarantee completion in the near future.
2. Assist you with a set of hook solutions so that the engine can read the translated strings without modifying the original script. This solution is more feasible.

**Comment by linakima** [comment]
@xmoezzz 
I would be happy with any solution. 
Could you explain how to translate the game using hooks?

**Comment by imKota** [comment]
@xmoezzz Don't help him. He does machine translations even if someone translates normally, thus hindering normal translators. Who may still end up quitting translations.

Сим, не мешай нормальным переводчикам.

**Comment by xmoezzz** [comment]
Although I strongly discourage the use of machine translation. However, I have still decided to provide the tool. Here are two tools: one is a disassembler, and the other is an assembler, which can extract the binary script file from FVP engine into project files and assemble the extracted project files back into the binary script file. 

This assembler not only restores translated strings back into the file, but also performs **complete instruction assembly operations**. If you're not familiar with FVP instructions, please refrain from modifying those instructions and their corresponding parameters casually.

This project is part of RFVP, which aims to achieve an open-source, cross-platform engine built with Rust through reverse engineering to analyze the behavior of the original engine.

https://github.com/xmoezzz/rfvp/tree/main/disassembler
https://github.com/xmoezzz/rfvp/tree/main/assembler

**Comment by xmoezzz** [comment]
For game translation, repackaging scripts is a more elegant approach. Typically, modifying the original engine requires a translation team to have a programmer skilled in reverse engineering. However, standardizing the translation process can significantly lower this barrier.

To those who love VN games and selflessly contribute.

**Comment by xmoezzz** [comment]
It looks like there hasn't been any further discussion on this issue for a while, so I'm closing it now.
